version: '3.8'

services:
  # Наш сервис RefferentCOREServer
  rcs:
    build: .
    container_name: rcs_server
    ports:
      - "8080:8080"
    # ### ИЗМЕНЕНИЕ: Конец ###
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - persona_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Сервис Redis
  redis:
    image: "redis:7-alpine"
    container_name: rcs_redis
    networks:
      - persona_network

networks:
  persona_network:
    driver: bridge
