version: '3.8'

services:
  # Наш сервис RefferentCOREServer
  rcs:
    build: .
    container_name: rcs_server
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - persona_network
    # ### ИЗМЕНЕНИЕ: Начало ###
    # Добавляем эту секцию, чтобы ws://host.docker.internal работал на всех платформах, включая Linux.
    # 'host-gateway' - это специальное значение, которое Docker заменяет
    # на внутренний IP-адрес хост-машины.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ### ИЗМЕНЕНИЕ: Конец ###

  # Сервис Redis
  redis:
    image: "redis:7-alpine"
    container_name: rcs_redis
    networks:
      - persona_network

networks:
  persona_network:
    driver: bridge
